= clc project (Beta)

Project commands are a group of project operations.

Usage:

[source,bash]
----
clc project [command] [flags]
----

== Commands

* <<clc-project-create, clc project create>>

== clc project create

Creates project from the given template.

Usage:

[source,bash]
----
clc project create [template-name] [output-dir] [vars] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`output-dir`
|Required
|Output directory for the project to be created.
|

|`template-name`
|Required
|Name of the template.
|

|`vars`
|Optional
|Variables can be defined to be used in templates as key-value pairs. Example: `key`=`value`

WARNING: keys cannot contain punctuation
|
|===

=== Creating and Using Your Own Templates
Templates are located under https://github.com/hazelcast-templates  organization by default. You can override it by using `CLC_EXPERIMENTAL_TEMPLATE_SOURCE` environment variable.

==== Rules while creating your own templates:
* Templates are in link:.https://pkg.go.dev/text/template[Go template] format.
* You can create a `defaults.yaml` file for default values in template's root directory.
* Template files must have the `.template` extension.
* Files with `.` and `_` prefixes are ignored by default. If want to keep them you must add `.keep` extension to them.
* Other files are copied verbatim.

==== Properties are read from the following resources in order:
1. `defaults.yaml` (keys cannot contain punctuation)
2. `config.yaml`
3. User passed key-values (keys cannot contain punctuation)

You can use the placeholders in "defaults.yaml" and the following configuration item placeholders:

* ClusterName
* ClusterAddress
* ClusterUser
* ClusterPassword
* ClusterDiscoveryToken
* SslEnabled
* SslServer
* SslSkipVerify
* SslCaPath
* SslKeyPath
* SslKeyPassword
* LogPath
* LogLevel

Example (Linux and MacOS):

[source,bash]
----
export CLC_EXPERIMENTAL_TEMPLATE_SOURCE=https://github.com/my-template-organization
clc project create \
simple-streaming-pipeline-template\
my-project\
MyKey1=MyValue1 MyKey2=MyValue2
----

Example (Windows):

[source,bash]
----
set CLC_EXPERIMENTAL_TEMPLATE_SOURCE=https://github.com/my-template-organization
clc project create^
simple-streaming-pipeline-template^
my-project^
MyKey1=MyValue1 MyKey2=MyValue2
----