= clc project (Beta)

Project commands are a group of project operations.

Usage:

[source,bash]
----
clc project [command] [flags]
----

== Commands

* <<clc-project-create, clc project create>>

== clc project create

Creates project from the given template.

Usage:

[source,bash]
----
clc project create [template-name] [placeholder-values] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--output-dir`, `-o`
|Optional
|Output directory for the project to be created.
|Template name

|`template-name`
|Required
|Name of the template.
|

|`placeholder-values`
|Optional
|Template placeholder values can be specified as key-value pairs. You can use lowercase letters, numbers and the underscore character in keys. Example: `key`=`value`

|
|===

=== Creating and Using Your Own Templates

Templates are located in https://github.com/hazelcast-templates. You can override it by using `CLC_EXPERIMENTAL_TEMPLATE_SOURCE` environment variable.

==== Rules while creating your own templates:

* Templates are in link:.https://pkg.go.dev/text/template[Go template] format.
* You can create a "defaults.yaml" file for default values in template's root directory.
* Template files must have the ".template" extension.
* Files with "." and "_" prefixes are ignored unless they have the ".keep" extension.
* All files with ".keep" extension are copied by stripping the ".keep" extension.
* Other files are copied verbatim.

==== Properties are read from the following resources in order:

1. `defaults.yaml` (keys cannot contain punctuation)
2. `config.yaml`
3. User passed key-values in the "KEY=VALUE" format. The keys can only contain lowercase letters, numbers and the underscore character.

You can use the placeholders in "defaults.yaml" and the following configuration item placeholders:

* cluster_name
* cluster_address
* cluster_user
* cluster_password
* cluster_discovery_token
* ssl_enabled
* ssl_server
* ssl_skip_verify
* ssl_ca_path
* ssl_key_path
* ssl_key_password
* log_path
* log_level

Example (Linux and MacOS):

[source,bash]
----
clc project create \
simple-streaming-pipeline\
--output-dir my-project\
my_key1=my_value1 my_key2=my_value2
----

Example (Windows):

[source,bash]
----
clc project create^
simple-streaming-pipeline^
--output-dir my-project^
my_key1=my_value1 my_key2=my_value2
----