= clc project (Beta)

Project commands are a group of project operations.

Usage:

[source,bash]
----
clc project [command] [flags]
----

== Commands

* <<clc-project-create, clc project create>>

== clc project create

Creates project from the given template. It reads placeholder values from multiple resources, in order:

- `defaults.yaml` file, which maybe included in the template repository.
- `config.yaml` file, included in `$HOME/.hazelcast/config/<config-name>` directory.
- User defined variables.

=== Using Configuration Variables
You can use the variables in `defaults.yaml` and `config.yaml` by specifying them in templates as placeholders in camel case format. For example, if you have the following variable in one of the configuration files:
```
cluster:
    name: my-cluster
```
Then you can use it in templates as `ClusterName`.


Usage:

[source,bash]
----
clc project create [template-name] [output-dir] [vars] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`output-dir`
|Required
|Output directory for the project to be created.
|

|`template-name`
|Required
|Name of the template.
|

|`vars`
|Optional
|Variables can be defined to be used in templates as key-value pairs. Example: `key`=`value`

WARNING: key cannot contain punctuation
|
|===

=== Creating and Using Your Own Templates
Templates are located under %s by default, however you can override it by using `CLC_EXPERIMENTAL_TEMPLATE_SOURCE` env variable.

==== Rules while creating your own templates:
- Templates are in link:.https://pkg.go.dev/text/template[Go template] format.
- You can create a `defaults.yaml` file for default values in template's root directory.
- Template files must have the `.template` extension.
- Files with `.` and `_` prefixes are ignored by default but, if want to keep them, you must add `.keep` extension to them.
- Other files are copied verbatim.

==== Properties are read from the following resources in order:
1. `defaults.yaml` (keys cannot contain punctuation)
2. `config.yaml`
3. User passed key-values (keys cannot contain punctuation)