= clc viridian

This command group provides commands for doing various {hazelcast-cloud} operations, such as creating and managing clusters.

All commands except `viridian login` require the generation of a token using an API key and secret, which you can retrieve from the {hazelcast-cloud} console. Running `viridian login` prompts you for this information, and creates and saves the token.

Usage:

[source,bash]
----
clc viridian [command] [options]
----

== Commands

* <<clc-viridian-login, clc viridian login>>
* <<clc-viridian-list-cluster-types, clc viridian list-cluster-types>>
* <<clc-viridian-create-cluster, clc viridian create-cluster>>
* <<clc-viridian-get-cluster, clc viridian get-cluster>>
* <<clc-viridian-list-clusters, clc viridian list-clusters>>
* <<clc-viridian-stop-cluster, clc viridian stop-cluster>>
* <<clc-viridian-resume-cluster, clc viridian resume-cluster>>
* <<clc-viridian-delete-cluster, clc viridian delete-cluster>>
* <<clc-viridian-download-logs, clc viridian download-logs>>
* <<clc-viridian-stream-logs, clc viridian stream-logs>>
* <<clc-viridian-import-config, clc viridian import-config>>
* <<clc-viridian-list-custom-classes, clc viridian list-custom-classes>>
* <<clc-viridian-upload-custom-class, clc viridian upload-custom-class>>
* <<clc-viridian-download-custom-class, clc viridian download-custom-class>>
* <<clc-viridian-delete-custom-class, clc viridian delete-custom-class>>

== clc viridian login

Logs in to {hazelcast-cloud} using the given API key and API secret and retrieves a token. The token is cached to be used by other commands. If not specified, the key and the secret will be asked for in a prompt.

Alternatively, you can use the following environment variables:

* `CLC_VIRIDIAN_API_KEY`
* `CLC_VIRIDIAN_API_SECRET`

Usage:

[source,bash]
----
clc viridian login [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, an input prompt is shown.
|

|`--api-secret`
|Optional
|Sets the API secret. Overrides the `CLC_VIRIDIAN_API_SECRET` environment variable. If not given, an input prompt is shown.
|

|===

== clc viridian list-cluster-types

Lists available cluster types you can use to create a {hazelcast-cloud} cluster.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian list-cluster-types [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|===

== clc viridian create-cluster

Creates a {hazelcast-cloud} cluster.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian create-cluster [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|`--name`
|Optional
|Sets the name of the created cluster. If not given, an auto-generated name will be used.
|

|`--cluster-type`
|Optional
|Sets the cluster-type for the created cluster.
|

|===

== clc viridian get-cluster

Gets the information about the given {hazelcast-cloud} cluster.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian get-cluster [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|===

== clc viridian list-clusters

Lists all {hazelcast-cloud} clusters for the logged in API key.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian list-clusters [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|===

== clc viridian stop-cluster

Stops the given {hazelcast-cloud} cluster.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian stop-cluster [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|===

== clc viridian resume-cluster

Resumes the given {hazelcast-cloud} cluster.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian resume-cluster [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|===

== clc viridian delete-cluster

Deletes the given {hazelcast-cloud} cluster. Note that, all data in the cluster is deleted irreversibly.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian delete-cluster [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|`--yes`
|Optional
|Skips confirming the delete operation.
|

|===

== clc viridian download-logs

Downloads the logs of the given {hazelcast-cloud} cluster.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian download-logs [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|`--output-dir` `-o`
|Optional
|Output directory for the log files, if not given current directory is used.
|

|===

== clc viridian stream-logs

Outputs the logs of the given {hazelcast-cloud} cluster as a stream.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

The log format may be one of:

* minimal: Only the log message
* basic: Time, level and the log message
* detailed: Time, level, thread, logger and the log message
* free form template, see: https://pkg.go.dev/text/template for the format.
You can use the following placeholders: `msg`, `level`, `time`, `thread` and `logger`.
Usage:

[source,bash]
----
clc viridian stream-logs [cluster-ID/name] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|

|`--log-format`
|Optional
|Format of log lines. Either a predefined or free form format.
|`basic`

|===

== clc viridian import-config

Imports connection configuration of the given {hazelcast-cloud} cluster.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc import-config [cluster-name/cluster-ID] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, one of the existing API keys will be used.
|
|===


== clc viridian list-custom-classes

Lists all custom classes in the {hazelcast-cloud} cluster.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian list-custom-classes [cluster-name/cluster-ID] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--verbose`
|Optional
|Prints additional column `Temporary Custom Classes ID`
|

|===

== clc viridian upload-custom-class

Uploads a custom class to the {hazelcast-cloud} cluster.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian upload-custom-class [cluster-name/cluster-ID] [file-name] [flags]
----

== clc viridian download-custom-class

Downloads a custom class from the {hazelcast-cloud} cluster.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian download-custom-class [cluster-name/cluster-ID] [file-name/artifact-ID] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--output-path`
|Optional
|Output path for the downloaded artifact. The base directory of the path is created recursively if it doesn't exist.
|

|===

== clc viridian delete-custom-class

Deletes a custom class from the {hazelcast-cloud} cluster.

Make sure you authenticate with the {hazelcast-cloud} API using `viridian login` before running this command.

Usage:

[source,bash]
----
clc viridian delete-custom-class [cluster-name/cluster-ID] [file-name/artifact-ID] [flags]
----