= clc viridian

This command group provides commands for doing various Viridian operations, such as creating and managing clusters.

Usage:

[source,bash]
----
clc viridian [command] [options]
----

== Commands

* <<clc-viridian-login, clc viridian login>>
* <<clc-viridian-list-clusters, clc viridian list-clusters>>
* <<clc-viridian-list-custom-classes, clc viridian list-custom-classes>>
* <<clc-viridian-upload-custom-class, clc viridian upload-custom-class>>
* <<clc-viridian-download-custom-class, clc viridian download-custom-class>>
* <<clc-viridian-delete-custom-class, clc viridian delete-custom-class>>

== clc viridian login

Logs in to Viridian using the given API key and API secret and retrieves a token.
The token is cached to be used by other commands.
If not specified, the key and the secret will be asked in a prompt.

Alternatively, you can use the following environment variables:

* `CLC_VIRIDIAN_API_KEY`
* `CLC_VIRIDIAN_API_SECRET`

Usage:

[source,bash]
----
clc viridian login [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--api-key`
|Optional
|Sets the API key. Overrides the `CLC_VIRIDIAN_API_KEY` environment variable. If not given, an input prompt is shown.
|

|`--api-secret`
|Optional
|Sets the API secret. Overrides the `CLC_VIRIDIAN_API_SECRET` environment variable. If not given, an input prompt is shown.
|

|===

== clc viridian list-clusters

Lists all Viridian clusters for the logged in API key.

Make sure you login before running this command.

Usage:

[source,bash]
----
clc viridian list-clusters [flags]
----

== clc viridian list-custom-classes

Lists all custom classes in the Viridian cluster.

Make sure you login before running this command.

Usage:

[source,bash]
----
clc viridian list-custom-classes [cluster-name/cluster-ID] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--verbose`
|Optional
|Prints additional column `Temporary Custom Classes ID`
|

|===

== clc viridian upload-custom-class

Uploads a custom class to the Viridian cluster.

Make sure you login before running this command.

Usage:

[source,bash]
----
clc viridian upload-custom-class [cluster-name/cluster-ID] [file-name] [flags]
----

== clc viridian download-custom-class

Downloads a custom class from the Viridian cluster.

Make sure you login before running this command.

Usage:

[source,bash]
----
clc viridian download-custom-class [cluster-name/cluster-ID] [file-name/artifact-ID] [flags]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--output-path`
|Optional
|Output path for the downloaded artifact. The base directory of the path is created recursively if it doesn’t exist.
|

|===

== clc viridian delete-custom-class

Deletes a custom class from the Viridian cluster.

Make sure you login before running this command.

Usage:

[source,bash]
----
clc viridian delete-custom-class [cluster-name/cluster-ID] [file-name/artifact-ID] [flags]
----