= Configuring Hazelcast CLC
:description: Hazelcast CLC allows you to configure cluster connection settings, using command-line parameters or a configuration file.

{description}

Hazelcast CLC evaluates configuration settings in the following precedence, with items higher on the list taking priority:

. Command-line parameters
. Values in the configuration file

== CLC Configuration File

The CLC configuration file contains all settings that are used for connecting Hazelcast CLC to either a Hazelcast Platform or Hazelcast Cloud cluster.

The default configuration file is located at `/.local/share/hz-cli/config.yaml`. This file configures Hazelcast CLC to open an unencrypted connection to a cluster at localhost:5701. If your cluster uses <<tls, TLS authentication>>, you can configure TLS settings.

Configuration files are written in the YAML file format.

To change the configuration settings, you can either edit the default configuration file, or create your own and use the `-c` flag to pass it to Hazelcast CLC:

`hzc -c /some/custom/config.yaml`

== CLC Configuration with Command-Line Parameters

Command-line parameters are for overriding some configuration settings in the configuration file.

You can override the values in the configuration file by providing the following command-line parameters to any `hzc` command:

[tabs] 
==== 
Platform:: 
+ 
--
include::partial$global-parameters.adoc[!*]
--
Cloud:: 
+ 
--
include::partial$global-parameters.adoc[]
--
====

[[tls]]
== TLS Authentication

If your cluster members use TLS to communicate with each other or clients, you need to configure Hazelcast CLC with TLS settings. Hazelcast CLC supports the following TLS authentication:

- One-way authentication
- Mutual authentication
- No TLS verification for self-signed certificates

=== Connecting to Clusters with One-Way Authentication

Hazelcast Platform clusters can have one-way TLS authentication enabled. However, Hazelcast Cloud cluster always use <<mutual, mutual authentication>>.

[tabs] 
==== 
Platform:: 
+ 
--
[source,yaml]
----
ssl:
  enabled: true
hazelcast:
  cluster:
    security:
      credentials:
        username: "<OPTIONAL USERNAME>"
        password: "<OPTIONAL PASSWORD>"
    name: "<CLUSTER-NAME>"
    network:
    addresses:
    - "<MEMBER IP ADDRESS>"
----
--
Cloud:: 
+ 
--
Not supported. See <<mutual, mutual authentication>>.
--
====

[[mutual]]
=== Connecting to Clusters Using Mutual TLS Authentication

If clusters accept TLS connections only from trusted clients, you must provide a trusted TLS certificate for the Hazelcast CLC.

[tabs] 
==== 
Platform:: 
+ 
--
[source,yaml]
----
ssl:
  enabled: true
  servername: "<HOSTNAME-FOR-CLUSTER CERTIFICATE>"
  capath: "/tmp/ca.pem"
  certpath: "/tmp/cert.pem"
  keypath: "/tmp/key.pem"
  keypassword: "<PASSWORD FOR THE KEY>"
hazelcast:
  cluster:
    security:
      credentials:
        username: "<OPTIONAL USERNAME>"
        password: "<OPTIONAL PASSWORD>"
    name: "<CLUSTER-NAME>"
    network:
      addresses:
        - "<MEMBER IP ADDRESS>"
----
--

Cloud:: 
+ 
--
[source,yaml]
----
ssl:
  enabled: true
  capath: "/tmp/ca.pem"
  capath: "/tmp/ca.pem"
  certpath: "/tmp/cert.pem"
  keypath: "/tmp/key.pem"
  keypassword: "<PASSWORD FOR THE KEY>"
hazelcast:
  cluster:
    name: "<CLUSTER NAME>"
    cloud:
      token: "<DISCOVERY TOKEN>"
      enabled: true
----
--
====

=== Connecting to Clusters with Self-Signed TLS Certificates

If your cluster members use self-signed TLS certificates, you can use the `insecureskipverify` setting to skip TLS verification and avoid connection errors.

WARNING: Skipping TLS verification makes you vulnerable to man-in-the-middle attacks because any device can act as the intended cluster.

[tabs] 
==== 
Platform:: 
+ 
--
[source,yaml]
----
ssl:
  enabled: true
  insecureskipverify: true
hazelcast:
  cluster:
    security:
      credentials:
        username: "<OPTIONAL USERNAME>"
        password: "<OPTIONAL PASSWORD>"
    name: "<CLUSTER-NAME>"
    network:
    addresses:
    - "<MEMBER IP ADDRESS>"
----
--

Cloud:: 
+ 
--
[source,yaml]
----
ssl:
  enabled: true
  insecureskipverify: true
  capath: "/tmp/ca.pem"
  capath: "/tmp/ca.pem"
  certpath: "/tmp/cert.pem"
  keypath: "/tmp/key.pem"
  keypassword: "<PASSWORD FOR THE KEY>"
hazelcast:
  cluster:
    name: "<CLUSTER NAME>"
    cloud:
      token: "<DISCOVERY TOKEN>"
      enabled: true
----
--
====