== CLC Configuration Wizard

:description: Hazelcast CLC provides a wizard functionlity in the interactice mode to manage multiple configuration easily. It runs when a client connection need and asks for a configuration choice.

:page-product: cloud

{description}

If you don't have any configuration yet, it will show a prompt screen to enter a configuration source with target name. If you have configurations
in the Hazelcast CLC home directory, it will list them and ask for you to select one to create client connection.

TIP: If you have a configuration named `default`, a configuration YAML exists next to executable or in the current working directory,
CLC directly uses it instead of running configuration wizard.

== Before you Begin

You need the following:

- Hazelcast CLC
- A {hazelcast-cloud} cluster

== Connecting to {hazelcast-cloud}

. Start the Hazelcast CLC in interactive mode.
+
```bash
$ clc
```
+

. Execute an operation that requires a client connection to cluster.
+
```bash
CLC> SHOW MAPPINGS;
```
+

. CLC will scan the configurations and list them if there is any. If there is no configuration found, it will prompt an
input screen for you to import a new configuration.
+
```bash
There is no configuration detected. You can register a new configuration to conn
You can connect to Viridian cluster using curl request from `Dashboard -> Connec
Paste the link to source field below and it will download the config and TLS fil

Configuration Name: default
Source:

[ Submit ]
```
+

. Specify the name of the configuration by chancing the configuration name field. The default value is `default`
If there is any default configuration, CLC will use it automatically.
+
```bash
Configuration Name: default
```
+

. Copy the Go Client sample url from {hazelcast-cloud} console.

. Paste the Go client sample CURL request link to `Source: ` in this screen.
+
```bash
Source: curl https://api.viridian.hazelcast.com/client_samples/download/...
```
+
. Press `[ Submit ]` and it will automatically connect to your Viridian cluster. Notice that if you didn't specify the
configuration name or leave it as default, it will automatically connect to this client unless you specify it with `--config` flag.

== Multiple Configurations

If you have multiple configurations in the CLC home directory, the configuration wizard will prompt you the list of
configuration to select. You can select by using your arrow keys.

. Start the Hazelcast CLC in interactive mode.
+
```bash
$ clc
```
+

. Execute an operation that requires a client connection to cluster.
+
```bash
CLC> SHOW MAPPINGS;
```
+

. CLC will scan the configurations and list them if there is any.
+
```bash
1. viridian-prod-config
2. viridian-dev-config
3. remote-cluster-config
```
+

. Move using arrow keys and press Enter for the configuration you want to use.

NOTE: The Hazelcast CLC connects to the cluster on demand, that is when you issue a command that requires the connection, such as running a SQL query.