= Configuration for Hazelcast CLC
:description: Hazelcast CLC allows you to configure settings for cluster connection credentials, using a configuration file. Some of those settings may be overriden using global command-line parameters.

{description}

CLC has a simple YAML configuration, usually named `config.yaml`.
This file can exist anywhere in the file system, and can be used with the `--config` (or `-c`) flag:
[source, bash]
----
clc -c test/config.yaml
----

`configs` directory in `$CLC_HOME` is special, it contains all the configurations known to CLC. You can use the `clc home` command in order to see where `$CLC_HOME` is:
[source, bash]
----
clc home
/home/me/.local/share/clc
----

Known configurations can be directly specified by their names, instead of the full path.
`clc config list` command lists the configurations known to CLC:
[source, bash]
----
# List configurations
$ clc config list
default
pr-3066

# Start CLC shell with configuration named pr-3066
$ clc -c pr-3066
----

If no configuration is specified, the `default` configuration is used.
The name of the default configuration may be overriden using the `CLC_CONFIG` environment variable.

If there's only a single named configuration, then it is used if the configuration is not specified with `-c`/`--config`.

== CLC Configuration with Command-Line Parameters

Command-line parameters are for overriding some configuration settings in the configuration file, such as the log settings.

You can override the values in the configuration file by providing the following command-line parameters to any `clc` command:

include::partial$global-parameters.adoc[]

== Related Resources

- xref:connect-to-viridian.adoc[Connecting to {hazelcast-cloud} with Hazelcast CLC].

- xref:connect-to-platform.adoc[Connecting to Hazelcast Platform with Hazelcast CLC].

