= Configuration for Hazelcast CLC
:description: Hazelcast CLC allows you to configure settings for cluster connection credentials, using a configuration file. Some of those settings may be overriden using global command-line parameters.

{description}

CLC has a simple YAML configuration, usually named `config.yaml`.
This file can exist anywhere in the file system, and can be used with the `--config` (or `-c`) flag:
[source, bash]
----
clc -c test/config.yaml
----

//TIP: If you don't add any configuration before and try to run an operation that requires client connection, CLC will prompt a configuration wizard to import Viridian config easily. For details, see xref:config-wizard.adoc[CLC Configuration Wizard ].


If there is a `config.yaml` in the same directory with the CLC binary and the configuration was not explicitly set, CLC tries to load that configuration file:
[source, bash]
----
ls -lh
total 17M
-rwxrwxr-x 1 yuce yuce  17M Nov 26 23:11 clc*
-rw------- 1 yuce yuce  200 Nov 26 23:12 config.yaml
----

`configs` directory in `$CLC_HOME` is special, it contains all the configurations known to CLC. You can use the `clc home` command in order to see where `$CLC_HOME` is:
[source, bash]
----
clc home
/home/me/.local/share/clc
----

Known configurations can be directly specified by their names, instead of the full path.
`clc config list` command lists the configurations known to CLC:
[source, bash]
----
# List configurations
$ clc config list
default
prod

# Start CLC shell with configuration named pr-3066
$ clc -c prod
----

If no configuration is specified, the `default` configuration is used.

== CLC Configuration with Command-Line Parameters

Command-line parameters are for overriding some configuration settings in the configuration file, such as the log settings.

You can override the values in the configuration file by providing the following command-line parameters to any `clc` command:

include::partial$global-parameters.adoc[]

== Related Resources

//- xref:connect-to-viridian.adoc[].

- xref:connect-to-platform.adoc[].

