== Connecting to {hazelcast-cloud} with Hazelcast CLC
:description: To use the Hazelcast CLC with {hazelcast-cloud}, you can import CLC configuration from a Viridian cluster. You don’t need to do any configuration.

:page-product: cloud

{description}

You can also create a cluster using CLC, which automatically makes the cluster configuration available. See Managing Viridian Clusters for more information.

== Before you Begin

You need the following:

- Hazelcast CLC
- A {hazelcast-cloud} cluster
- Viridian API key and secret

TIP: You can create and find the API key and secret in the {hazelcast-cloud} console. For details, see xref:cloud:ROOT:developer.adoc[].

[[mutual]]
== Retrieving the Viridian token

. Retrieve the Viridian token using the following command:
+
```bash
clc viridian login
```
+
Enter your API key and secret when asked. If the API key and secret is correct, the Viridian token will be retrieved and stored.

[[mutual]]
== Listing the Clusters

. Run the following command in order to list the clusters your account can access:
+
```bash
clc viridian list-clusters
```

[[mutual]]
== Importing the Configuration

. Import the configuration with name `dev` from the Viridian cluster:
+
```bash
clc viridian import-config CLUSTER-NAME --name dev
```
. Start an interactive shell session.
+
```bash
clc -c dev
```

CLC will start in the interactive mode, and you should see a command prompt.

NOTE: The Hazelcast CLC connects to the cluster on demand, that is when you issue a command that requires the connection, such as running a SQL query.