== Connecting to Hazelcast {hazelcast-cloud} with Hazelcast CLC
:description: To use the Hazelcast CLC with Hazelcast {hazelcast-cloud}, you can download a preconfigured client. You don't need to do any configuration.

:page-product: cloud

{description}

The xref:configuration.adoc[configuration file] in a sample client provides the Hazelcast CLC with with the correct connection credentials.

== Before you Begin

You need the following:

- Hazelcast CLC
- A {hazelcast-cloud} cluster

TIP: You can find all connection credentials, such as the cluster name and discovery token, in the {hazelcast-cloud} console. For details, see xref:cloud:ROOT:connect-to-cluster.adoc[].

[[mutual]]
== Connecting to Clusters

Make sure that your cluster is running before you start.

. link:https://viridian.hazelcast.com/[Sign in to {hazelcast-cloud}] and select your cluster.

. From the cluster dashboard, click *CLI* to open the *Quick Connection Guide* for the Hazelcast CLC client.

. Run the `clc config import` command in step 2. This command updates the cluster configuration on your local machine.

. Run the `clc -c pr-<CLUSTER_ID>` command in step 3 to connect to your cluster using the Hazelcast CLC.
+
CLC will start in the interactive mode, and you should see a CLC prompt.

NOTE: The Hazelcast CLC connects to the cluster on demand, that is when you issue a command that requires the connection, such as running a SQL query.