= Connecting to Hazelcast Platform with Hazelcast CLC
:description: To use Hazelcast CLC with Hazelcast Platform, you need to configure it with the correct connection credentials.
:page-product: platform

{description}

The configuration examples in this topic use a xref:configuration.adoc[configuration file].

== Before you Begin

You need the following:

- Hazelcast CLC
- A Hazelcast Platform cluster
- Your cluster's connection credentials:

** *Cluster name:* To find your cluster name, see xref:hazelcast:clusters:creating-clusters.adoc[`cluster-name` configuration].
** *IP addresses:* If you're not connecting to a local member at localhost:5701 (default), you'll need the IP addresses of the members that you want to connect to.
** *Username and password:* If your cluster is configured with simple authentication, find the username and password in your member configuration file. See xref:hazelcast:security:simple-authentication.adoc[].
** *Mutual TLS:* If your cluster is configured with mutual TLS authentication, you'll need your client TLS keys and certificates. See xref:hazelcast:security:tls-ssl.adoc#mutual-authentication[Mutual Authentication].

Hazelcast CLC supports the following TLS connections for Hazelcast Platform:

- <<one-way, One-way authentication>>
- <<mutual, Mutual authentication>>
- <<no-verify, No TLS verification>> for self-signed certificates
- <<none, No TLS authentication>>

[[one-way]]
== Connecting to Clusters with One-Way Authentication

. Add the following to your configuration file:
+
[source,yaml]
----
ssl:
  enabled: true
  servername: "<HOSTNAME IN CLUSTER CERTIFICATE>"
hazelcast:
  cluster:
    security:
      credentials:
        username: "<OPTIONAL USERNAME>"
        password: "<OPTIONAL PASSWORD>"
    name: "<CLUSTER NAME>"
    network:
    addresses:
    - "<MEMBER IP ADDRESS>"
----

. Start an interactive shell session.
+
```bash
hzc
```

If the connection is successful, you should see a command prompt.

If you see `ERROR: cannot connect`, make sure that you are using the correct configuration.

[[mutual]]
== Connecting to Clusters with Mutual TLS Authentication

. Add the following to your configuration file:
+
[source,yaml]
----
ssl:
  enabled: true
  servername: "<HOSTNAME IN CLUSTER CERTIFICATE>"
  capath: "/<PATH>/ca.pem"
  certpath: "/<PATH>/cert.pem"
  keypath: "/<PATH>/key.pem"
  keypassword: "<PASSWORD FOR THE KEY>"
hazelcast:
  cluster:
    security:
      credentials:
        username: "<OPTIONAL USERNAME>"
        password: "<OPTIONAL PASSWORD>"
    name: "<CLUSTER NAME>"
    network:
      addresses:
        - "<MEMBER IP ADDRESS>"
----

. Start an interactive shell session.
+
```bash
hzc
```

If the connection is successful, you should see a command prompt.

If you see `ERROR: cannot connect`, make sure that you are using the correct configuration.

[[no-verify]]
== Connecting to Clusters with Self-Signed TLS Certificates

If your cluster members use self-signed TLS certificates, you can use the `insecureskipverify` setting to skip TLS verification and avoid connection errors.

WARNING: Skipping TLS verification makes you vulnerable to man-in-the-middle attacks because any device can act as the intended cluster.

. Add the following to your configuration file:
+
[source,yaml]
----
ssl:
  enabled: true
  insecureskipverify: true
hazelcast:
  cluster:
    security:
      credentials:
        username: "<OPTIONAL USERNAME>"
        password: "<OPTIONAL PASSWORD>"
    name: "<CLUSTER NAME>"
    network:
    addresses:
    - "<MEMBER IP ADDRESS>"
----

. Start an interactive shell session.
+
```bash
hzc
```

If the connection is successful, you should see a command prompt.

If you see `ERROR: cannot connect`, make sure that you are using the correct configuration.

[[none]]
== Connecting to Clusters with TLS Disabled

. Add the following to your configuration file:
+
[source,yaml]
----
ssl:
  enabled: false
hazelcast:
  cluster:
    security:
      credentials:
        username: "<OPTIONAL USERNAME>"
        password: "<OPTIONAL PASSWORD>"
    name: "<CLUSTER NAME>"
    network:
    addresses:
    - "<MEMBER IP ADDRESS>"
----

. Start an interactive shell session.
+
```bash
hzc
```

If the connection is successful, you should see a command prompt.

If you see `ERROR: cannot connect`, make sure that you are using the correct configuration.

== Next Steps

See the xref:clc-commands.adoc[command reference] to learn what you can do with Hazelcast CLC.