== Connecting to {hazelcast-cloud} with Hazelcast CLC
:description: To use the Hazelcast CLC with Hazelcast {hazelcast-cloud}, you need to authenticate with {hazelcast-cloud} using your API secret and key. You can then import the configuration of the {hazelcast-cloud} cluster that you want to connect to. No additional configuration is required.

:page-product: cloud

{description}

You can also create a cluster using CLC, which automatically makes the cluster configuration available. See Managing {hazelcast-cloud} Clusters for more information.

== Before you Begin

You need the following:

- Hazelcast CLC
- A {hazelcast-cloud} cluster
- xref:cloud:ROOT:developer.adoc[{hazelcast-cloud} API key and secret]

[[mutual]]
== Authenticating with {hazelcast-cloud}

To allow the Hazelcast CLC to do cluster operations, you must generate a {hazelcast-cloud} token.

. Execute the following command to retrieve the {hazelcast-cloud} token.
+
```bash
clc viridian login
```
+
. When prompted, enter your API key and secret. If both are correct, the token is retrieved and saved.

[[mutual]]
== List Accessible Clusters

Run the following command to list the clusters linked to your Hazelcast {hazelcast-cloud} account:

```bash
clc viridian list-clusters
```

For each cluster, the following attributes are displayed in order: Cluster ID, Cluster Name, Current Status, Hazelcast Version.


[[mutual]]
== Importing the Configuration

. Import the connection configuration from the {hazelcast-cloud} cluster and save it with name `dev` using the command below. Use the name of your cluster instead `CLUSTER-NAME`:
+
```bash
clc viridian import-config CLUSTER-NAME --name dev
```
. Start an interactive shell session.
+
```bash
clc -c dev
```

CLC will start in the interactive mode, and you should see a command prompt.

NOTE: The Hazelcast CLC connects to the cluster on demand, that is when you issue a command that requires the connection, such as running a SQL query.