= Connecting to Hazelcast Platform with Hazelcast CLC
:description: To use the Hazelcast CLC with Hazelcast Platform, you need to configure it with the correct connection credentials.
:page-product: platform

{description}

The configuration examples in this topic use a xref:configuration.adoc[configuration file].

== Before you Begin

You need the following:

- Hazelcast CLC
- A Hazelcast Platform cluster
- Your cluster's connection credentials:

** *Cluster name:* To find your cluster name, see xref:hazelcast:clusters:creating-clusters.adoc[`cluster-name` configuration].
** *IP addresses:* If you're not connecting to a local member at localhost:5701 (default), you'll need the IP addresses of the members that you want to connect to.
** *Username and password:* If your cluster is configured with simple authentication, find the username and password in your member configuration file. See xref:hazelcast:security:simple-authentication.adoc[].
** *Mutual TLS:* If your cluster is configured with mutual TLS authentication, you'll need your client TLS keys and certificates. See xref:hazelcast:security:tls-ssl.adoc#mutual-authentication[Mutual Authentication].

Hazelcast CLC supports the following TLS connections for Hazelcast Platform:

- <<one-way, One-way authentication>>
- <<mutual, Mutual authentication>>
- <<no-verify, No TLS verification>> for self-signed certificates
- <<none, No TLS authentication>>

[[one-way]]
== Connecting to Clusters with One-Way Authentication

. Add the following to your configuration file:
+
[source,yaml]
----
cluster:
  name: "<CLUSTER NAME>"
  address: "<MEMBER IP ADDRESS>"
  user: "<OPTIONAL USERNAME>"
  password: "<OPTIONAL PASSWORD>"
ssl:
  enabled: true
  server: "<HOSTNAME IN CLUSTER CERTIFICATE>"
----

. Start an interactive shell session.
+
```bash
clc
```

The Hazelcast CLC starts in interactive mode at a command prompt.

NOTE: The Hazelcast CLC connects to the cluster on demand, that is when you issue a command that requires the connection, such as running a SQL query.

[[mutual]]
== Connecting to Clusters with Mutual TLS Authentication

. Add the following to your configuration file:
+
[source,yaml]
----
cluster:
  name: "<CLUSTER NAME>"
  address: "<MEMBER IP ADDRESS>"
credentials:
  user: "<OPTIONAL USERNAME>"
  password: "<OPTIONAL PASSWORD>"
ssl:
  enabled: true
  server: "<HOSTNAME IN CLUSTER CERTIFICATE>"
  ca-path: "/<PATH>/ca.pem"
  cert-path: "/<PATH>/cert.pem"
  key-path: "/<PATH>/key.pem"
  key-password: "<PASSWORD FOR THE KEY>"
----

. Start an interactive shell session.
+
```bash
clc
```

Hazelcast CLC starts in interactive mode at a command prompt.

NOTE: Hazelcast CLC connects to the cluster on demand, that is when you issue a command that requires the connection, such as running a SQL query.

[[no-verify]]
== Connecting to Clusters with Self-Signed TLS Certificates

If your cluster members use self-signed TLS certificates, you can use the `skip-verify` setting to skip TLS verification and avoid connection errors.

WARNING: Skipping TLS verification makes you vulnerable to man-in-the-middle attacks because any device can act as the intended cluster.

. Add the following to your configuration file:
+
[source,yaml]
----
cluster:
  name: "<CLUSTER NAME>"
  address: "<MEMBER IP ADDRESS>"
credentials:
  user: "<OPTIONAL USERNAME>"
  password: "<OPTIONAL PASSWORD>"
ssl:
  enabled: true
  skip-verify: true
----

. Start an interactive shell session.
+
[source,bash]
----
clc
----

CLC will start in the interactive mode, and you should see a command prompt.

NOTE: Hazelcast CLC connects to the cluster on demand, that is when you issue a command that requires the connection, such as running a SQL query.

[[none]]
== Connecting to Clusters with TLS Disabled

. Add the following to your configuration file:
+
[source,yaml]
----
cluster:
  name: "<CLUSTER NAME>"
  address: "<MEMBER IP ADDRESS>"
credentials:
  user: "<OPTIONAL USERNAME>"
  password: "<OPTIONAL PASSWORD>"
----

. Start an interactive shell session.
+
```bash
clc
```

The Hazelcast CLC starts in the interactive mode at a command prompt.

NOTE: Hazelcast CLC connects to the cluster on demand, that is when you issue a command that requires the connection, such as running a SQL query.

== Next Steps

See the xref:clc-commands.adoc[command reference] to learn what you can do with Hazelcast CLC.