== Connecting to {hazelcast-cloud} with Hazelcast CLC
:description: To use Hazelcast CLC with {hazelcast-cloud}, you need to configure it with the correct connection credentials.
:page-product: cloud

{description}

The configuration examples in this topic use a xref:configuration.adoc[configuration file] to configure Hazelcast CLC.

== Before you Begin

You need the following:

- Hazelcast CLC
- A {hazelcast-cloud} cluster
- Your cluster's connection credentials

TIP: You can find all connection credentials such as the cluster name and discovery token in the {hazelcast-cloud} console. For details, see xref:cloud:connect-to-cluster.adoc[].

[[mutual]]
== Connecting to Clusters with Mutual TLS Authentication

. Add the following to your configuration file:
+
[source,yaml]
----
ssl:
  enabled: true
  capath: "/<PATH>/ca.pem"
  certpath: "/<PATH>/cert.pem"
  keypath: "/<PATH>/key.pem"
  keypassword: "<PASSWORD FOR THE KEY>"
hazelcast:
  cluster:
    name: "<CLUSTER NAME>"
    cloud:
      token: "<DISCOVERY TOKEN>"
      enabled: true
----

. Start an interactive shell session.
+
```bash
hzc
```

If the connection is successful, you should see a command prompt.

If you see `ERROR: cannot connect`, make sure that you are using the correct configuration.

[[none]]
== Connecting to Clusters with TLS Disabled

. Add the following to your configuration file:
+
[source,yaml]
----
ssl:
  enabled: false
hazelcast:
  cluster:
    name: "<CLUSTER NAME>"
    cloud:
      token: "<DISCOVERY TOKEN>"
      enabled: true
----

. Start an interactive shell session.
+
```bash
hzc
```

If the connection is successful, you should see a command prompt.

If you see `ERROR: cannot connect`, make sure that you are using the correct configuration.

== Next Steps

See the xref:clc-commands.adoc[command reference] to learn what you can do with Hazelcast CLC.
