== Connecting to {hazelcast-cloud} with Hazelcast CLC
:description: To use Hazelcast CLC with {hazelcast-cloud}, you need to configure it with the correct connection credentials.
:page-product: cloud

{description}

The configuration examples in this topic use a xref:configuration.adoc[configuration file] to configure Hazelcast CLC.

== Before you Begin

You need the following:

- Hazelcast CLC
- A {hazelcast-cloud} cluster

TIP: You can find all connection credentials such as the cluster name and discovery token in the {hazelcast-cloud} console. For details, see xref:cloud:ROOT:connect-to-cluster.adoc[].

[[mutual]]
== Connecting to Clusters

. Download the Go Client sample from {hazelcast-cloud} console.

. Import the configuration from the sample as `dev`:
+
```bash
clc config dev import PATH-TO-GO-CLIENT-SAMPLE.zip
```
. Start an interactive shell session.
+
```bash
clc -c dev
```

CLC will start in the interactive mode, and you should see a command prompt.

Note that, CLC connects to the cluster on demand, that is when you issue a command that requires the connection, such as running SQL queries.
