= Get Started With the Hazelcast CLC
:description: In this tutorial, you'll learn the basics of how to configure the Hazelcast CLC, start it, and connect it to a Hazelcast {hazelcast-cloud} Serverless development cluster and a Serverless production cluster. You'll also see how to switch between clusters, using the Hazelcast CLC. Finally, you'll perform some basic operations on a cluster from the command line and then by running a script to automate the same actions.

{description}

== Before You Begin

You need the following:

- The xref:install-clc.adoc[Hazelcast CLC] installed on your local machine
- Two xref:cloud:ROOT:create-serverless-cluster.adoc[Hazelcast {hazelcast-cloud} Serverless clusters]. For this tutorial, you'll use one development and one production cluster, to show how you might use the CLC for basic administration and deployment tasks.
- Go Client samples for your clusters.

TIP: You can download Go client samples from Hazelcast {hazelcast-cloud} console. For details, see xref:cloud:ROOT:connect-to-cluster.adoc[].

[[step-1-dev-config]]
== Step 1. Configure the Hazelcast CLC for a Viridian Cluster

Before you can connect the Hazelcast CLC to your Viridian cluster, you need to add cluster's configuration.

CLC can use a Viridian Go Client sample to discover the configuration for your Viridian cluster.
Simply download the Go Client sample from Viridian console.
Once the sample is downloaded, you can use the `clc config import` command to import the configuration.

Assuming the Go client sample for your Viridian cluster was saved to the `Downloads` folder in your home directory, run the following command to create the `dev` configuration:

On Linux and MacOS:
[source, bash]
----
clc config import -c dev ~/Downloads/hazelcast-cloud-go-sample-client-pr-XXXX-default.zip
----

On Windows:
[source, bash]
----
clc config import -c dev %USERPROFILE%/Downloads/hazelcast-cloud-go-sample-client-pr-XXXX-default.zip
----

You can use the `clc config list` command to confirm that the configuration was imported.
[source, bash]
----
clc config list
default
dev
----

From now on, use the `-c` flag with the name of the configuration to tell CLC to use your Viridian cluster.

[[step-2-dev-connect]]
== Step 2. Connect the Hazelcast CLC to the Development Cluster

You're ready to connect the Hazelcast CLC to your development cluster. Make sure that the cluster is running before you start.

. Download the Go Client sample for your development cluster from the Viridian cluster.
. From the command line, execute the following command, replacinf `PATH-TO-SAMPLE.zip` with the path to the downloaded sample:

+
[source, bash]
----
clc config import -c dev PATH-TO-SAMPLE.zip
clc -c dev
----

+
CLC connects to the cluster only when necessary.
Run a command that requires a connection to the cluster, such as `object list`:

+
[source, clc]
----
CLC> \object list
Connected to cluster: pr-3814

------------------------------------
 Service Name | Object Name
------------------------------------
 executor     | hot-backup-executor
 map          | cities
 map          | default
------------------------------------
----

+
. Press kbd:[Ctrl+D] or type `\exit` to shut down Hazelcast CLC while you complete the configuration for your production cluster.

[[step-3-prod-configure]]
== Step 3. Add Configuration for the Production Cluster

The configuration of the production cluster is the same as the previous step, but using the production cluster configuration.

Make sure that your Viridian production cluster is running before you start.

. Download the Go Client sample for your production cluster from the Viridian cluster.
. From the command line, execute the following command, replacinf `PATH-TO-SAMPLE.zip` with the path to the downloaded sample:

+
[source, bash]
----
clc config import -c prod PATH-TO-SAMPLE.zip
clc -c prod
----

+
CLC connects to the cluster only when necessary.
Run a command that requires a connection to the cluster, such as `object list`:

+
[source, clc]
----
CLC> \object list
Connected to cluster: pr-3690

------------------------------------
 Service Name | Object Name
------------------------------------
 executor     | hot-backup-executor
------------------------------------
----

[[step-4-cluster-switch]]
== Step 4. Switch Between Clusters

Having separate local configurations for your development and production clusters allows you to switch between them without leaving the command line. Make sure both clusters are running before you start.

. Execute the following command to use the `dev` configuration to connect to your development cluster:
+
[source, bash]
----
clc -c dev
----

+
As before, the Hazelcast CLC connects to your development cluster.
. Type `\exit` to return to the command line.
. Execute the following command to use the new configuration file for your production cluster.
+
[source, bash]
----
clc -c prod
----
+
The Hazelcast CLC shell is started, using the configuration for the production cluster.

[[step-5-write-data]]
== Step 5. Write Data to a Map

Now that you've connected to both your clusters, try using the Hazelcast CLC to write data to a map on your development cluster.
Let's write a script that adds some data to a map.

. Copy the following lines to a file in `data.sql`.
+
.data.sql
[source]
----
\map put -c dev -n currency -k i32 1 -v json '{"Code": "CAD", "Currency": "Canadian Dollar"}'
\map put -c dev -n currency -k i32 2 -v json '{"Code": "INR", "Currency": "Indian Rupee"}'
\map put -c dev -n currency -k i32 3 -v json '{"Code": "MXN", "Currency": "Mexican Peso"}'
\map put -c dev -n currency -k i32 4 -v json '{"Code": "GBP", "Currency": "Pounds Sterling"}'
\map put -c dev -n currency -k i32 5 -v json '{"Code": "TRY", "Currency": "Turkish Lira"}'
\map put -c dev -n currency -k i32 6 -v json '{"Code": "USD", "Currency": "United States Dollar"}'
----

. Run the script in `data.sql` to update the `currency` map:
+
On Linux and MacOS:
+
[source,bash]
----
cat data.sql | clc -c dev
----
+
On Windows:
+
[source,bash]
----
type data.sql | clc -c dev
----
+
. Do a quick check on your cluster to make sure that your data has been written successfully.
. Open the dashboard of the development cluster and click *Management Center*.
. Go to *Storage* > *Maps*. You'll see that your cluster has a map called `currency` with six entries. 

[[step-6-query-map]]
== Step 6. Query Map Data
You can use SQL to query the data in your `currency` map.

. Start by creating a mapping to the `currency` map.

+
[source,bash]
----
clc sql -c dev "CREATE MAPPING currency (__key VARCHAR, Code VARCHAR, Currency VARCHAR) TYPE IMap OPTIONS('keyFormat'='varchar', 'valueFormat'='json-flat')"
----
The SQL mapping statement does a number of things:

** Adds column headings for currencies and codes
** Creates a SQL connection to the map
** Tells Hazelcast how to serialize and deserialize the keys and values.

. Try running some simple queries against the `currency` map. For example, this query returns all data in the map and orders it by the currency code.  
+
[source,bash]
----
clc sql "SELECT * FROM currency ORDER BY Code"
----
+
The results look like this:

+
[source,shell]
----
+------------+--------------------+--------------------+
|__key       |Code                |Currency            |
+------------+--------------------+--------------------+
|1           |CAD                 |Canadian Dollar     |
|4           |GBP                 |Pounds Sterling     |
|2           |INR                 |Indian Rupee        |
|3           |MXN                 |Mexican Peso        |
|5           |TRY                 |Turkish Lira        |
|6           |USD                 |United States Dollar|
+------------+--------------------+--------------------+

----

[[step-7-automate]]
== Step 7. Automate Actions

When you're ready, combine the commands that you've learned about so far into a shell script and run them from the command line. 

The script first writes the currency data to a new map called `currencydata` on your development server, queries it and then switches to your production cluster to perform the same actions.

[tabs] 
==== 
Linux and MacOS::
+ 
--
. Copy the following commands into a shell script.
+
.myscript.sh
[source,bash]
----
#!/usr/bin/bash
map put -c dev -n currency -k i32 1 -v json '{"Code": "CAD", "Currency": "Canadian Dollar"}'
map put -c dev -n currency -k i32 2 -v json '{"Code": "INR", "Currency": "Indian Rupee"}'
map put -c dev -n currency -k i32 3 -v json '{"Code": "MXN", "Currency": "Mexican Peso"}'
map put -c dev -n currency -k i32 4 -v json '{"Code": "GBP", "Currency": "Pounds Sterling"}'
map put -c dev -n currency -k i32 5 -v json '{"Code": "TRY", "Currency": "Turkish Lira"}'
map put -c dev -n currency -k i32 6 -v json '{"Code": "USD", "Currency": "United States Dollar"}'
hzc sql -c dev "CREATE MAPPING currencydata (__key VARCHAR, Code VARCHAR, Currency VARCHAR) TYPE IMap OPTIONS('keyFormat'='varchar', 'valueFormat'='json-flat')"
hzc sql -c dev "SELECT * FROM currencydata ORDER BY Code"

map put -c prod -n currency -k i32 1 -v json '{"Code": "CAD", "Currency": "Canadian Dollar"}'
map put -c prod -n currency -k i32 2 -v json '{"Code": "INR", "Currency": "Indian Rupee"}'
map put -c prod -n currency -k i32 3 -v json '{"Code": "MXN", "Currency": "Mexican Peso"}'
map put -c prod -n currency -k i32 4 -v json '{"Code": "GBP", "Currency": "Pounds Sterling"}'
map put -c prod -n currency -k i32 5 -v json '{"Code": "TRY", "Currency": "Turkish Lira"}'
map put -c prod -n currency -k i32 6 -v json '{"Code": "USD", "Currency": "United States Dollar"}'
hzc -c prod sql "CREATE MAPPING currencydata (__key VARCHAR, Code VARCHAR, Currency VARCHAR) TYPE IMap OPTIONS('keyFormat'='varchar', 'valueFormat'='json-flat')"
hzc -c prod sql "SELECT * FROM currencydata ORDER BY Code"
----

. Save your script as `myscript.sh`.
. Use the following command to make sure that the script is executable:
+
```bash
chmod 777 myscript.sh
```
. Then, to run the script, execute the following command:
+
```bash
./myscript.sh
```
--
Windows::
+ 
--
. Copy the following commands into a batch file.
+
.myscript.bat
[source,bash]
----
map put -c dev -n currency -k i32 1 -v json '{"Code": "CAD", "Currency": "Canadian Dollar"}'
map put -c dev -n currency -k i32 2 -v json '{"Code": "INR", "Currency": "Indian Rupee"}'
map put -c dev -n currency -k i32 3 -v json '{"Code": "MXN", "Currency": "Mexican Peso"}'
map put -c dev -n currency -k i32 4 -v json '{"Code": "GBP", "Currency": "Pounds Sterling"}'
map put -c dev -n currency -k i32 5 -v json '{"Code": "TRY", "Currency": "Turkish Lira"}'
map put -c dev -n currency -k i32 6 -v json '{"Code": "USD", "Currency": "United States Dollar"}'
hzc sql -c dev "CREATE MAPPING currencydata (__key VARCHAR, Code VARCHAR, Currency VARCHAR) TYPE IMap OPTIONS('keyFormat'='varchar', 'valueFormat'='json-flat')"
hzc sql -c dev "SELECT * FROM currencydata ORDER BY Code"

map put -c prod -n currency -k i32 1 -v json '{"Code": "CAD", "Currency": "Canadian Dollar"}'
map put -c prod -n currency -k i32 2 -v json '{"Code": "INR", "Currency": "Indian Rupee"}'
map put -c prod -n currency -k i32 3 -v json '{"Code": "MXN", "Currency": "Mexican Peso"}'
map put -c prod -n currency -k i32 4 -v json '{"Code": "GBP", "Currency": "Pounds Sterling"}'
map put -c prod -n currency -k i32 5 -v json '{"Code": "TRY", "Currency": "Turkish Lira"}'
map put -c prod -n currency -k i32 6 -v json '{"Code": "USD", "Currency": "United States Dollar"}'
hzc -c prod sql "CREATE MAPPING currencydata (__key VARCHAR, Code VARCHAR, Currency VARCHAR) TYPE IMap OPTIONS('keyFormat'='varchar', 'valueFormat'='json-flat')"
hzc -c prod sql "SELECT * FROM currencydata ORDER BY Code"
----

. Save your script as `myscript.bat`.
. Run the script:
+
```bash
myscript.bat
```

--
====

== Summary

In this tutorial, you learned how to do the following:

* Connect to a Hazelcast {hazelcast-cloud} Serverless development cluster.
* Connect to a Hazelcast {hazelcast-cloud} Serverless production cluster.
* Switch between clusters from the command line.
* Write data to a map and query the data using SQL.
* Automate commands by running a sequence of actions from a shell script.

== Learn More

Use these resources to continue learning:

- xref:configuration.adoc[].

- xref:clc-commands.adoc[].

- xref:clc-sql.adoc[].

