= hzc cluster

Cluster commands are a group of administrative cluster operations.

NOTE: You cannot use cluster commands on {hazelcast-cloud} clusters. To manage these clusters using the command-line, see link:https://github.com/hazelcast/hazelcast-cloud-cli[{hazelcast-cloud} CLI].

== Prerequisites

* You must xref:hazelcast:maintain-cluster:rest-api.adoc#enabling-rest-api[enable the REST API] on all members of your cluster to use the commands.
* You must also xref:hazelcast:maintain-cluster:rest-api.adoc#enabling-endpoint-groups[enable] the `CLUSTER_WRITE` endpoint group for the <<hzc-cluster-change-state, change-state>> and <<hzc-cluster-shutdown, shutdown>> commands.

== Commands

* <<hzc-cluster-get-state, hzc cluster get-state>>
* <<hzc-cluster-change-state, hzc cluster change-state>>
* <<hzc-cluster-shutdown, hzc cluster shutdown>>
* <<hzc-cluster-version, hzc cluster version>>

== hzc cluster get-state

Prints the state of cluster. See xref:hazelcast:maintain-cluster:cluster-member-states.adoc#cluster-states[Cluster States] for the descriptions of each state.

Usage:

[source,bash]
----
hzc cluster get-state
----

== hzc cluster change-state

Changes the state of cluster.

Usage:

[source,bash]
----
hzc cluster change-state
----

== hzc cluster shutdown

Shuts down the cluster.

Usage:

[source,bash]
----
hzc cluster shutdown
----

== hzc cluster version

Prints the version of your running Hazelcast Platform cluster.

Usage:

[source,bash]
----
hzc cluster version
----
