= hzc map

Map commands are a group of map operations.

== Commands

* <<hzc-map-clear, hzc map clear>>
* <<hzc-map-get, hzc map get>>
* <<hzc-map-get-all, hzc map get-all>>
* <<hzc-map-put, hzc map put>>
* <<hzc-map-put-all, hzc map put-all>>
* <<hzc-map-remove, hzc map remove>>
* <<hzc-map-use, hzc map use>>

== hzc map clear

Deletes all entries from the map.

Usage:

[source,bash]
----
hzc map clear --name <name of your map>
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--name`, `-n`
|Required
|Name of the map.
|`dev`

|===

== hzc map get

Prints a single entry from the map as a key-value pair.

Usage:

[source,bash]
----
hzc map get --name
            --key
            [--key-type {string (default), boolean, json, int8, int16, int32, int64, float32, float64}]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--name`, `-n`
|Required
|Name of the map.
|`dev`

|`--key`, `-k`
|Required
|Key of the map entry.
|N/A

|`--key-type`
|Optional
|Data type of the key.
|String

|===

Example:

[source,bash]
----
hzc map get --name yearbook --key 2012 --key-type int16
---

== hzc map get-all

Prints all the entries for the given keys from the map as key-value pairs.

Usage:

[source,bash]
----
hzc map get-all --name
                --key
                [--key-type {string (default), boolean, json, int8, int16, int32, int64, float32, float64}]
                [--delim {":" (default)}]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--name`, `-n`
|Required
|Name of the map.
|`dev`

|`--key`, `-k`
|Required
|Key of the map entry.
|N/A

|`--key-type`
|Optional
|Data type of the key.
|String

|`--delim`
|Optional
|Delimiter to separate the printed key and value.
|:

|===

Example:

[source,bash]
----
hzc get-all -n yearbook -k 2012 -k 2013 --key-type int16 --delim ":"
----

== hzc map put

Sets the value of a given key in a map.

Usage:

[source,bash]
----
hzc map put --name
            --key
            --value
            [--value-file]
            [--key-type {string (default), boolean, json, int8, int16, int32, int64, float32, float64}]
            [--value-type {string (default), boolean, json, int8, int16, int32, int64, float32, float64}]
            [--max-idle {ns, us, ms, s, m, h (nanosecond, microsecond, millisecond, second, minute, hour)}]
            [--ttl {ns, us, ms, s, m, h (nanosecond, microsecond, millisecond, second, minute, hour)}]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--name`, `-n`
|Required
|Name of the map.
|`dev`

|`--key`, `-k`
|Required
|Key of the map entry.
|N/A

|`--value`, `-v`
|Required
|Value to set for the key. Mutually exclusive with `--value-file`.
|N/A

|`--value-file`, `-f`
|Optional
|Path to a file that contains the value to set for the key. Use `-` (dash) to read from `stdin`. Mutually exclusive with `--value`.
|N/A

|`--key-type`
|Optional
|Data type of the key.
|String

|`--value-type`, `-t`
|Optional
|Data type of the value.
|String

|`--max-idle`
|Optional
|Maximum time in milliseconds for the entry to stay idle in the map. It cannot be shorter than 1 second (1000 ms).
|N/A

|`--ttl`
|Optional
|Duration in milliseconds after which the entry will expire and be evicted. It cannot be shorter than 1 second (1000 ms).
|N/A

|===

Example:

[source,bash]
----
hzc map put --key-type string --key hello --value-type float32 --value 19.94 --name myMap --ttl 1300ms --max-idle 1400ms
---

== hzc map put-all

Add the given key-value entry pairs to a map.

Usage:

[source,bash]
----
hzc map put-all --name
            --key
            --value
            [--value-file]
            [--key-type {string (default), boolean, json, int8, int16, int32, int64, float32, float64}]
            [--value-type {string (default), boolean, json, int8, int16, int32, int64, float32, float64}]
            [--max-idle {ns, us, ms, s, m, h (nanosecond, microsecond, millisecond, second, minute, hour)}]
            [--ttl {ns, us, ms, s, m, h (nanosecond, microsecond, millisecond, second, minute, hour)}]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--name`, `-n`
|Required
|Name of the map.
|`dev`

|`--key`, `-k`
|Required
|Key of the map entry.
|N/A

|`--value`, `-v`
|Required
|Value to set for the key. Mutually exclusive with `--value-file`.
|N/A

|`--value-file`, `-f`
|Optional
|Path to a file that contains the value to set for the key. Use `-` (dash) to read from `stdin`. Mutually exclusive with `--value`.
|N/A

|`--key-type`
|Optional
|Data type of the key.
|String

|`--value-type`, `-t`
|Optional
|Data type of the value.
|String

|`--json-entry`
|Optional
|Path to a JSON file that contains entries. Mutually exclusive with `--value`, `--value-file`, and `--value-type`.
|N/A

|===

Example:

[source,bash]
----
# Keys and values are matched with the given order
hzc map put-all --name mapname --key-type int16 --key 1 --key 2 --value-type json --value-file valueFile.json --value '{"field":"tmp"}'
---

Example using `json-entry`:

[source,bash]
----
hzc map put-all --name mapname --json-entry entries.json
---

Example JSON file:

[source,json]
----
{
  "key1": "value1",
  "key2": {
    "innerData": "data",
    "anotherInnerData": 5.0
  },
  "key3": true,
  "key4": [1, 2, 3, 4, 5]
}
----

== hzc map remove

Deletes the value of a given key in a map.

Usage:

[source,bash]
----
hzc map remove --name
               --key
               [--key-type {string (default), boolean, json, int8, int16, int32, int64, float32, float64}]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--name`, `-n`
|Required
|Name of the map.
|`dev`

|`--key`, `-k`
|Required
|Key of the map entry.
|N/A

|`--key-type`
|Optional
|Data type of the key.
|String

|===

Example:

[source,bash]
----
hzc map remove --name mapname --key k1
----

== hzc map use

Sets the default map name. This command can be used only in the interactive mode (???link???).

Usage:

[source,bash]
----
hzc map use <new map name>
            [--reset]
----

Parameters:

[cols="1m,1a,2a,1a"]
|===
|Parameter|Required|Description|Default

|`--reset`
|Optional
|Unsets the default name for the map.
|N/A
|===

Example:

[source,bash]
----
hzc map use m1           # sets the default map name to m1 unless set explicitly in a parameter
hzc map get --key k1     # "--name m1" is inferred
hzc map use --reset      # resets the default map name
----












