= Installing the Hazelcast CLC
:description: The Hazelcast Command-Line Client (CLC) is available to install in macOS, Linux and Windows environments.

// See https://docs.hazelcast.com/hazelcast/5.2-snapshot/clients/clc#installing-the-hazelcast-clc

{description} You can install the Hazelcast CLC, using one of the following:

* Homebrew (recommended)
* Installer script
* Building from source

== Before You Begin

See the following prerequisites for each installation option and operating system requirements.

[tabs] 
==== 
Supported Operating Systems:: 
+ 
-- 
* Ubuntu 18.04 or newer
* MacOS 12 or newer
* Windows 10 or newer
--

Installer Script:: 
+ 
-- 
Installer script uses `curl` which is readily available on macOS computers.
For Linux, follow the instructions https://everything.curl.dev/get/linux[here] if it is not already installed.
--

Homebrew::
+
Follow the instructions https://docs.brew.sh/Installation[here] if it is not already installed on your macOS or Linux computer.

Build from Source::
+
If you prefer to install CLC by building it from its source on GitHub, you need to have the following installed on your machine:

* https://www.atlassian.com/git/tutorials/install-git[Git]
* https://www.gnu.org/software/make/[GNU Make]
* https://go.dev/doc/install[Go v1.18] or newer
====

== Installing Hazelcast CLC

You can install the Hazelcast CLC locally on macOS, Linux, and Windows environments.

[tabs] 
==== 
Installer Script (macOS, Linux):: 
+ 
-- 
[source,bash]
----
curl https://raw.githubusercontent.com/hazelcast/hazelcast-commandline-client/main/scripts/install.sh | bash
----
--

Installer (Windows)::
+
The installer for Windows is located https://github.com/hazelcast/hazelcast-commandline-client/releases[here].
Download the `hazecast-clc.exe` file, run it and follow the instructions on the installation wizard.

Homebrew::
+
[source,bash]
----
brew tap hazelcast/homebrew-hz
brew install hazelcast-commandline-client
----

Build from Source::
+
. Clone the GitHub repository.
+
[source,shell]
----
git clone https://github.com/hazelcast/hazelcast-commandline-client.git
----
. Change into the `hazelcast-commandline-client` directory.
+
[source,shell]
----
cd hazelcast-commandline-client
----
. Run the following command to build CLC.
+
[source,shell]
----
make
----
====

NOTE: To take advantage of auto-completion support, follow the instructions that appear during installation.

== Uninstalling the Hazelcast CLC

Choose the option that corresponds to your installation method.

[tabs] 
==== 
Installer Script (macOS, Linux):: 
+ 
-- 
[source,bash]
----
~/.local/share/hz-cli/bin/uninstall.sh
----
--

Installer (Windows)::
+
. Go to **Start menu** -> **Windows Settings** -> **Apps**.
. Find Hazelcast CLC in the list.
. Right click on it and select **Uninstall**.
. Follow the uninstallation wizard.

Homebrew::
+
[source,bash]
----
brew uninstall hazelcast-commandline-client
brew untap hazelcast/homebrew-hz
----

Source::
+
Delete the `hazelcast-commandline-client` directory.
====


