= Installing the Hazelcast CLC
:description: The Hazelcast Command-Line Client (CLC) is available to install in macOS, Linux, and Windows environments.

// See https://docs.hazelcast.com/hazelcast/5.2-snapshot/clients/clc#installing-the-hazelcast-clc

{description} You can install the Hazelcast CLC, using one of the following:

* Homebrew (recommended)
* Installer script
* Building from source

== Installing on macOS

The Hazelcast CLC is supported on macOS 12 or newer versions.

[tabs] 
==== 
Installer Script::
+
--
macOS 12 or newer comes with cURL bundled with the operating system. You can directly run the following command.

[source,bash]
----
curl https://raw.githubusercontent.com/hazelcast/hazelcast-commandline-client/main/scripts/install.sh | bash
----
--

Homebrew::
+
. Make sure Homebrew is installed using the following command.
+
[source,bash]
----
brew -v
----
+
If installed, you'll get its version information. Otherwise, you'll receive an error stating the command is not found; install it following the https://docs.brew.sh/Installation[Homebrew documentation].
+
. Run the following commands on a terminal.
+
[source,bash]
----
brew tap hazelcast/homebrew-hz
brew install hazelcast-commandline-client
----
+
NOTE: To take advantage of auto-completion support, follow the instructions that appear during installation.

Build from Source::
+
. Make sure the following are installed:
** https://www.atlassian.com/git/tutorials/install-git[Git] (check with the `git --version` command)
** https://www.gnu.org/software/make/[GNU Make] (check with the `make --version` command)
** https://go.dev/doc/install[Go v1.18] or newer (check with the `go version` command)
+
. Clone the GitHub repository.
+
[source,shell]
----
git clone https://github.com/hazelcast/hazelcast-commandline-client.git
----
. Change into the `hazelcast-commandline-client` directory.
+
[source,shell]
----
cd hazelcast-commandline-client
----
. Run the following command to build the Hazelcast CLC.
+
[source,shell]
----
make
----
====

== Installing on Linux

The Hazelcast CLC is supported on Ubuntu 18.04 or newer versions.

[tabs] 
==== 
Installer Script:: 
+ 
--
. Make sure cURL is installed using the following command.
+
[source,bash]
----
curl -V
----
+
Note the capital `V` in the command. If installed, you'll get its version information. Otherwise, you'll receive an error stating the command is not found; install it following the https://everything.curl.dev/get/linux[cURL documentation].
+
. Run the following command on a terminal.
+
[source,bash]
----
curl https://raw.githubusercontent.com/hazelcast/hazelcast-commandline-client/main/scripts/install.sh | bash
----
--

Homebrew::
+
. Make sure Homebrew is installed using the following command.
+
[source,bash]
----
brew -v
----
+
If installed, you'll get its version information. Otherwise, you'll receive an error stating the command is not found; install it following the https://docs.brew.sh/Installation[Homebrew documentation].
+
. Run the following commands on a terminal.
+
[source,bash]
----
brew tap hazelcast/homebrew-hz
brew install hazelcast-commandline-client
----
+
NOTE: To take advantage of auto-completion support, follow the instructions that appear during installation.

Build from Source::
+
. Make sure the following are installed:
** https://www.atlassian.com/git/tutorials/install-git[Git] (check with the `git --version` command)
** https://www.gnu.org/software/make/[GNU Make] (check with the `make --version` command)
** https://go.dev/doc/install[Go v1.18] or newer (check with the `go version` command)
+
. Clone the GitHub repository.
+
[source,shell]
----
git clone https://github.com/hazelcast/hazelcast-commandline-client.git
----
. Change into the `hazelcast-commandline-client` directory.
+
[source,shell]
----
cd hazelcast-commandline-client
----
. Run the following command to build the Hazelcast CLC.
+
[source,shell]
----
make
----
====

== Uninstalling the Hazelcast CLC

Choose the option that corresponds to your installation method.

[tabs] 
==== 
Installer Script (macOS, Linux):: 
+ 
-- 
[source,bash]
----
~/.local/share/hz-cli/bin/uninstall.sh
----
--

Homebrew::
+
[source,bash]
----
brew uninstall hazelcast-commandline-client
brew untap hazelcast/homebrew-hz
----

Source::
+
Delete the `hazelcast-commandline-client` directory.
====


