= Installing the Hazelcast CLC
:description: The Hazelcast Command-Line Client (CLC) is available to install in macOS, Linux, and Windows environments.

// See https://docs.hazelcast.com/hazelcast/5.2-snapshot/clients/clc#installing-the-hazelcast-clc

{description} You can install the Hazelcast CLC, using one of the following:

* Downloading a pre-built binary
* Windows installer
* Building from source

== Installing on macOS

The Hazelcast CLC is supported on macOS 13 or newer versions.

[tabs]
====
ZIP (Intel)::
+
. Go to the https://github.com/hazelcast/hazelcast-commandline-client/releases/latest[latest release page], and locate the AMD compressed file (`hazelcast-clc_v{full-version}_darwin_amd64.zip`).
. Download and unzip the file.
. Optionally make `clc` available without using its full path. You can do that by moving `clc` to one of the directories in the  `$PATH` environment variable. `/usr/local/bin` is a safe choice.
+
[source,shell,subs="attributes"]
----
sudo mv hazelcast-clc_v{full-version}_darwin_amd64/clc /usr/local/bin
----

ZIP (Apple Silicon)::
+
. Go to the https://github.com/hazelcast/hazelcast-commandline-client/releases/latest[latest release page], and locate the ARM compressed file (`hazelcast-clc_v{full-version}_darwin_arm64.zip`).
. Download and unzip the file.
. Optionally make `clc` available without using its full path. You can do that by moving `clc` to one of the directories in the  `$PATH` environment variable. `/usr/local/bin` is a safe choice.
+
[source,shell,subs="attributes"]
----
sudo mv hazelcast-clc_v{full-version}_darwin_arm64/clc /usr/local/bin
----

Build from Source::
+
. Make sure the following are installed:
** GNU Make (check with the `make --version` command). If it is not already installed, you can install Xcode Command Line Tools Package.
+
[source,shell]
----
xcode-select --install
----
+
** https://go.dev/doc/install[Go {go-version}] or newer (check with the `go version` command)
+
. Go to the https://github.com/hazelcast/hazelcast-commandline-client/releases/latest[latest release page], and locate the compressed source file (`v{full-version}.zip`).
. Download and unzip the file.
. Change into the `hazelcast-commandline-client-{full-version}` directory.
+
[source,shell,subs="attributes"]
----
cd hazelcast-commandline-client-{full-version}
----
. Run the following command to build the Hazelcast CLC.
+
[source,shell,subs="attributes"]
----
CLC_VERSION=v{full-version} make
----
+
The `clc` binary is created in the `build` directory.
. Run the following command to start the Hazelcast CLC.
+
[source,shell]
----
./build/clc
----
+
. Optionally make `clc` available without using its full path. You can do that by moving `clc` to one of the directories in the  `$PATH` environment variable. `/usr/local/bin` is a safe choice.
+
[source,shell,subs="attributes"]
----
sudo mv ./build/clc /usr/local/bin
----

====

== Installing on Linux

The Hazelcast CLC runs on any recent Linux distribution. We test it on Ubuntu 22.04.

[tabs] 
====
Tarball (AMD64)::
+
. Go to the https://github.com/hazelcast/hazelcast-commandline-client/releases/latest[latest release page], and locate the tarball for Linux (`hazelcast-clc_v{full-version}_linux_amd64.tar.gz`).
. Download and unzip the file.
. Optionally make `clc` available without using its full path. You can do that by moving `clc` to one of the directories in the  `$PATH` environment variable. `/usr/local/bin` is a safe choice.
+
[source,shell,subs="attributes"]
----
sudo mv hazelcast-clc_v{full-version}_linux_amd64/clc /usr/local/bin
----

Build from Source::
+
. Make sure the following are installed:
** GNU Make (check with the `make --version` command). It is installed by default on most Linux distributions.
** https://go.dev/doc/install[Go {go-version}] or newer (check with the `go version` command)
+
. Go to the https://github.com/hazelcast/hazelcast-commandline-client/releases/latest[latest release page], and locate the source tarball (`v{full-version}.tar.gz`).
. Download and uncompress the file.
+
[source,shell,subs="attributes"]
----
tar xf v{full-version}.tar.gz
----
. Change into the `hazelcast-commandline-client-{full-version}` directory.
+
[source,shell,subs="attributes"]
----
cd hazelcast-commandline-client-{full-version}
----
. Run the following command to build the Hazelcast CLC.
+
[source,shell,subs="attributes"]
----
CLC_VERSION=v{full-version} make
----
+
The `clc` binary is created in the `build` directory.
. Run the following command to start the Hazelcast CLC.
+
[source,shell]
----
./build/clc
----
+
. Optionally make `clc` available without using its full path. You can do that by moving `clc` to one of the directories in the  `$PATH` environment variable. `/usr/local/bin` is a safe choice.
+
[source,shell,subs="attributes"]
----
sudo mv ./build/clc /usr/local/bin
----

====

== Installing on Windows

The Hazelcast CLC is supported on Windows 10 or newer versions. We provide pre-built binaries only for 64bit Intel/AMD architecture.

[tabs] 
==== 
Installer::
+
. Go to the https://github.com/hazelcast/hazelcast-commandline-client/releases/latest[latest release page], and locate the Windows installer file (`hazelcast-clc-setup-v{full-version}.exe`).
. Download and the run the installer on your system to start the installation wizard.
. Follow the steps on the wizard; when you see the "Completing the Hazelcast CLC Setup Wizard" dialog, press kbd:[Finish] to complete the installation.
. `clc.exe` is automatically added to the `PATH` environment variable, so it can be started in the terminal without its full path.
. Start the Hazelcast CLC from the start menu or by running the following command.
+
[source,shell]
----
clc.exe
----

ZIP::
+
. Go to the https://github.com/hazelcast/hazelcast-commandline-client/releases/latest[latest release page], and locate the Windows ZIP file (`hazelcast-clc_v{full-version}_windows_amd64.zip`).
. Download and unzip the file.
. Optionally make `clc.exe` available without using its full path. You can do that by adding the full path of the extracted directory to the `PATH` environment variable.

====

== Verifying the Hazelcast CLC Installation

To check whether the Hazelcast CLC is installed properly, run the following command on a terminal.

[source,shell]
----
clc version
----

You should see the Hazelcast CLC version information.

== Uninstalling the Hazelcast CLC

Choose the option that corresponds to your installation method.

[tabs] 
==== 
Windows::
+
. Go to *Apps & Features* setting (*Start menu* -> *Windows Settings* -> *Apps*).
. Locate *Hazelcast CLC version {full-version}* under *Apps & Features* list.
. Right-click on it and select *Uninstall*.
. Press kbd:[Yes] on the uninstallation dialog.

Release Package::
+
Delete the `hazelcast-commandline-client` directory.
====

== Next Steps

In this section you've learnt how to install the Hazelcast CLC on the supported operating systems.
To start using the Hazelcast CLC, check the following resources:

//* See xref:get-started.adoc[Get Started] for a complete introduction to the Hazelcast CLC.
* See xref:configuration.adoc[Configuration] to configure the details of the connection between the Hazelcast CLC and a Hazelcast Platform cluster.
* See xref:clc-commands.adoc[Command Reference] for a complete list and descriptions of commands you can use with the Hazelcast CLC.
