= Get Started With Hazelcast Jet Job Management
:description: In this tutorial, you'll learn the basics of how to manage Hazelcast stream-processing pipelines with CLC. You will connect to a Hazelcast cluster and submit a Jet Job. Also, you will learn how to list, restart and cancel jobs.

{description}

== Before You Begin

You need the following:

- The xref:install-clc.adoc[Hazelcast CLC] installed on your local machine
- One running Hazelcast cluster. You can create a xref:managing-viridian-clusters.adoc#creating-a-cluster-on-viridian[Viridian development cluster] with CLC.

[[step-1-dev-configure]]
== Step 1. Add Configuration for the Development Cluster

Connect to the cluster with the following command:

[tabs]
====
Viridian::
+
--
[source,shell]
----
clc viridian import config <VIRIDIAN_CLUSTER_NAME> --name dev
----
--
Other Clusters::
+
--
[source,shell]
----
clc config add dev cluster.name=<CLUSTER_NAME> cluster.address=<CLUSTER_ADDRESS>
----
--
====

[[step-2-build-jet-job]]
== Step 2. Build the Jet Job

We have a simple Jet pipeline that reads natural numbers from a source and filters out the non-prime numbers. Resulting prime numbers are then added into a Hazelcast map named `primes` with the timestamps as the value.

You can find the Jet job project in https://github.com/hazelcast/hazelcast-commandline-client[the CLC repository] under the path `examples/platform/simple-streaming-pipeline`.

Build the project with the following command.

[source,shell]
----
./gradlew shadowJar
----

[[step-3-submit-jet-job]]
== Step 3. Submit the Jet job

Submit the Jet job with the following command. It will wait for the job to be in the `RUNNING` state.
 
[source,shell]
----
clc -c dev job submit build/libs/simple-streaming-pipeline-1.0-SNAPSHOT-all.jar --name prime-job --wait 
----

Now, list the jobs in the cluster. You should see `prime-job` in the `RUNNING` state

[source,shell]
----
clc -c dev job list
----

See that the `primes` map is continuously updated with new prime numbers

[source,shell]
----
while true; do \
  clc -c dev map entry-set -n primes -f table; sleep 5; \
done
----

[[step-4-restart-jet-job]]
== Step 4. Restart the Jet job

Now, restart the Jet job.

[source,shell]
----
clc -c dev job restart prime-job
----

See that the smallest prime numbers are updated with new timestamps in the `primes` map. Restarting a job resets the source thus the job starts to overwrite the primes' timestamps.

[source,shell]
----
while true; do \
  clc -c dev map entry-set -n primes -f table; sleep 1; \
done
----

[[step-5-cancel-jet-job]]
== Step 5. Cancel the Jet job

Now, cancel the Jet job.

[source,shell]
----
clc -c dev job cancel prime-job
----

See that the `primes` map size is the same in size.

[source,shell]
----
while true; do \
  clc -c dev map size -n primes; sleep 5; \
done
----

== Summary

In this tutorial, you learned how to do the following:

* Connect to a Hazelcast cluster.
* Build and submit Hazelcast Jet pipelines.
* Manage Jet pipeline lifecycle with commands: list, restart, cancel.

== Learn More

Use these resources to continue learning:

- xref:configuration.adoc[].

- xref:clc-commands.adoc[].

- xref:clc-job.adoc[].

