= Get Started With Hazelcast Jet Job Management
:description: In this tutorial, you'll learn the basics of how to manage stream-processing pipelines using the Hazelcast CLC with Hazelcast {hazelcast-cloud}. You'll see how to connect to a {hazelcast-cloud} cluster and submit a sample Jet job that generates a stream of numbers. You'll also learn how to use simple commands to monitor and cancel jobs.

{description}

== Before You Begin

You need the following:

- xref:install-clc.adoc[Hazelcast CLC] installed on your local machine
- One running Hazelcast {hazelcast-cloud} cluster. You can create a xref:managing-viridian-clusters.adoc#creating-a-cluster-on-viridian[{hazelcast-cloud} development cluster] using the Hazelcast CLC.
- xref:cloud:ROOT:developer.adoc[{hazelcast-cloud} API key and secret]
- JRE 8 or above.
- Gradle 8 or above.

[[step-1-authenticating-with-viridian]]
== Step 1. Authenticating with {hazelcast-cloud}

To allow the Hazelcast CLC to perform cluster operations, including submitting Jet jobs, you must generate a {hazelcast-cloud} token.

. Execute the following command to retrieve the {hazelcast-cloud} token.
+
[source,shell]
----
clc viridian login
----

. When prompted, enter your API key and secret. If both are correct, the token is retrieved and saved.

[[step-2-list-cluster-details]]
== Step 2. List Cluster Details

Next, check that the Hazelcast CLC can access your cluster by running the following command:

[source,shell]
----
clc viridian list-clusters
----

The details of all clusters linked to your Hazelcast {hazelcast-cloud} account are returned, including the Cluster ID, Cluster Name, Current Status, Hazelcast Version.

[[step-3-dev-configure]]
== Step 3. Connect to Your Cluster

For Hazelcast CLC to connect to your development cluster, you need to import the cluster's configuration, including its connection details.

Run the following command to save the cluster configuration with the name `dev`. Replace the `$CLUSTER_NAME` placeholder with the name of your cluster, shown in the top-left corner of the dashboard.

[source,shell]
----
clc viridian import-config $CLUSTER_NAME --name dev
----

[[step-4-build-jet-job]]
== Step 4. Build the Jet Job

Now you're ready to build the sample Jet job.

. Clone the GitHub repository.
+
[tabs] 
====
HTTPS:: 
+ 
--
```bash
git clone https://github.com/hazelcast/hazelcast-commandline-client

cd hazelcast-commandline-client/examples/platform/simple-streaming-pipeline
```
--
SSH:: 
+ 
--
```bash
git clone git@github.com:hazelcast/hazelcast-commandline-client.git

cd hazelcast-commandline-client/examples/platform/simple-streaming-pipeline
```
--
====
+
. Build the project with the following command:
+

[source,shell]
----
gradle shadowJar
----

[[step-5-submit-jet-job]]
== Step 5. Submit and Monitor the Jet Job

Submitting the sample Jet job generates a stream of numbers and creates a link:https://hashids.org/[hashid] for each number. The number and hashid pair are then saved to a Map called `my-map`, with the number as the key and hashid as the value.

. Execute the following command to submit the Jet job:
+
[source,shell]
----
clc -c dev job submit build/libs/simple-streaming-pipeline-1.0-SNAPSHOT-all.jar --name simple-pipeline --wait
----
+
The Hazelcast CLC waits until the job starts to run.

. Now, list the jobs in the cluster. You should see `simple-pipeline` in a `RUNNING` state.
+
[source,shell]
----
clc -c dev job list
----
+
. See how the size of `my-map` increases as entries are written to it.
+
[tabs] 
==== 
Unix::
+
.	Create a new shell script in your favorite text editor. For example:
+
[source,shell]
----
vi monitor.sh
----
. Add the following:
+
[source,shell]
----
#! /bin/bash
while true; 
do clc -c dev map size -n my-map; sleep 3;
done
----

. Run your script.
+
[source,shell]
----
./monitor.sh
----
. Press kbd:[Ctrl + C] when you're ready to cancel the script.

Windows::
+
. Create a new batch file in your favorite text editor. For example:
+
[source,shell]
----
notepad monitor.bat
----
. Add the following:
+
[source,shell]
----
@echo off
:start
clc -c dev map size -n my-map
timeout 5
goto start
----
. Run the batch file.
+
[source,shell]
----
monitor
----
. Press kbd:[Ctrl + C] when you're ready to cancel the script.
====

[[step-6-cancel-jet-job]]
== Step 6. Cancel the Jet job

. Now, cancel the Jet job.
+
[source,shell]
----
clc -c dev job cancel simple-pipeline
----

. Run your script (from step 5) to see the size of `my-map` now.

== Summary

In this tutorial, you learned how to do the following:

* Connect to a Hazelcast cluster.
* Build and submit a Hazelcast Jet job to create a data pipeline.
* Manage the lifecycle of a Jet job using list and cancel commands.

== Learn More

Use these resources to continue learning:

- xref:configuration.adoc[].

- xref:clc-commands.adoc[].

- xref:clc-job.adoc[].

