= 5.2.0 Release Notes

== New Features

* CLC can now read data serialized using Compact Serialization and Portable automatically.
* Added the ability to select a configuration from a list or import a {hazelcast-cloud} configuration when a configuration is not provided in the shell mode.
* Added the `--quite` (shorthand `-q`) flag which suppresses unnecessary outputs. CLC outputs can be sometimes noisy, such as success message logs; you can use this flag for a more quiet output.
* Added the `CLC_CLIENT_NAME` environment variable which allows overriding the default client name.
* Added the `CLC_CLIENT_LABELS` environment variable which allows overriding the default client labels with a comma separated list of labels.

* Added support for link:https://hazelcast.com/products/viridian/[{hazelcast-cloud} Serverless].

* Added the following commands:

** `object list`: Lists the distributed data structures in the cluster.
** `completion`: Generates the autocompletion script for the specified shell, either Bash, Fish, Powershell or Zsh. Use `--help` for more information.
** `config add`: Adds configuration to the Hazelcast CLC. For example, to connect to a specific cluster.
** `config import`: Imports configuration into the Hazelcast CLC from various sources. Currently only the {hazelcast-cloud} Serverless Go Client sample is supported.
** `config list`: Lists known configurations.
** `home`: Outputs the Hazelcast CLC home directory, which stores all configuration, logs and other files.

* Added support for the following output formats, using the `--format` flag:

** CSV
** Delimited. Outputs with tab characters between fields. This is the default format when working in non-interactive mode.
** JSON
** Table. This is the default format when working in interactive mode.

* Added SQL shortcuts to the Hazelcast CLC shell:
** `\dm`: Lists mappings.
** `\dm MAPPING`: Displays information about a mapping.
** `\dm+ MAPPING`: Describes a mapping.

* Added the `--show-type` flag for map commands, which outputs the type of key and value even if they can't be decoded.

== Enhancements

* Removed the SQL browser.
* The interactive mode defaults to running SQL queries. Prefix CLC commands with a backslash `\`.
* Simplified the configuration format.
* Map commands no longer use a flag for the key and value. They are passed as positional arguments: `$ map set -n my-map my-key my-value`.
* The Map name is optional and defaults to `default`.
* Removed `map get-all`, `map put` and `map put-all` commands.
* Added the `map set` command.
* Auto-completion is disabled in interactive mode.
* {hazelcast-cloud} Serverless is the default cloud platform.
* The shell connects to the cluster on demand.

== Known issues

* Powershell autocompletion does not work.
* Ctrl+(left/right) key combinations don't work as expected in the interactive mode. You can set the `CLC_EXPERIMENTAL_READLINE` environment variable to ny to use an alternative readline implementation.
