# This workflow triggers a build of the production documentation site
# if a commit is made to the listed branches

name: Build production site

on:
  push:
    paths:
      - 'docs/**'
    branches: [ main, 'v/*' ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build
      run: curl -X POST -d {} https://api.netlify.com/build_hooks/63e51b633069a8009cc0ea22