name: "Release CLC"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: "write"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - name: "Set up Go"
        uses: "actions/setup-go@v3"
        with:
          go-version: "1.21"

      - name: "Build the Project"
        run: |
          go install golang.org/x/tools/...@latest
          go mod tidy
          export CLC_VERSION="${GITHUB_REF_NAME}"
          GOOS=linux GOARCH=amd64 make release BINARY_NAME=clc TARGZ=true
          GOOS=linux GOARCH=arm64 make release BINARY_NAME=clc TARGZ=true
          GOOS=linux GOARCH=arm make release BINARY_NAME=clc TARGZ=true
          GOOS=darwin GOARCH=amd64 make release BINARY_NAME=clc TARGZ=false
          GOOS=darwin GOARCH=arm64 make release BINARY_NAME=clc TARGZ=false
          GOOS=windows GOARCH=amd64 make release BINARY_NAME=clc.exe TARGZ=false
          echo "Release files:"
          cat build/release.txt

      - name: "Release tar.gz"
        uses: "softprops/action-gh-release@v1"
        with:
          files: "build/*.tar.gz"

      - name: "Release zip"
        uses: "softprops/action-gh-release@v1"
        with:
          files: "build/*.zip"
