name: "Release MC CLC"
on:
  push:
    tags:
      - "mc-v*"
permissions:
  contents: "write"
env:
  IS_MC_BUILD: 1
  CLC_VERSION: ${GITHUB_REF_NAME}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Set up Go"
        uses: "actions/setup-go@v3"
        with:
          go-version: "1.21"
      - name: "Build the Project"
        run: |
          go install golang.org/x/tools/...@latest
          go mod tidy
          GOOS=linux GOARCH=amd64 make mc-release BINARY_NAME=clc TARGZ=false
          GOOS=linux GOARCH=arm64 make mc-release BINARY_NAME=clc TARGZ=false
          GOOS=linux GOARCH=arm make mc-release BINARY_NAME=clc TARGZ=false
          GOOS=darwin GOARCH=amd64 make mc-release BINARY_NAME=clc TARGZ=false
          GOOS=darwin GOARCH=arm64 make mc-release BINARY_NAME=clc TARGZ=false
          echo "Release files:"
          cat build/release.txt

      - name: "Upload zip"
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: build/*.zip
