
name: "Test Hazelcast CLC 32bit"
on: ["push", "pull_request"]
jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    env:
      GOPATH: "${{ github.workspace }}"
      HZ_VERSION: "5.2.2"
      DEFAULT_TIMEOUT: "30s"
    defaults:
      run:
        shell: "bash"
        working-directory: "$HOME/hazelcast-commandline-client"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
        with:
          path: "$HOME/hazelcast-commandline-client"

      - name: "Setup JRE"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"

      - name: "Download RCD (Linux)"
        run: |
          wget https://rcd-download.s3.us-east-2.amazonaws.com/rcd-${{ matrix.os }}

      - name: "Start Hazelcast Remote Controller (Linux)"
        run: |
          chmod +x rcd-${{ matrix.os }} 
          ./rcd-${{ matrix.os }} -version $HZ_VERSION -dir $HOME &
          sleep 10

      - name: "Setup Go"
        uses: "actions/setup-go@v3"
        with:
          go-version: "1.19"

      - name: "Install Go tools"
        run: |
          go install golang.org/x/tools/...@v0.1.11
          go install honnef.co/go/tools/cmd/staticcheck@2022.1.2

      - name: "Go mod tidy"
        run: |
          go mod tidy

      - name: "Run All Tests"
        run: |
          GOARCH=386 make test
